CROSS_BUTTON = 0
CIRCLE_BUTTON = 1
SQUARE_BUTTON = 2
TRIANGLE_BUTTON = 3
SELECT_BUTTON = 4
PS_BUTTON = 5
OPTION_BUTTON = 6
START_BUTTON = OPTION_BUTTON
LS_BUTTON = 7
RS_BUTTON = 8
L1_BUTTON = 9
R1_BUTTON = 10
UP_BUTTON = 11
DOWN_BUTTON = 12
LEFT_BUTTON = 13
RIGHT_BUTTON = 14
MICROPHONE_BUTTON = 15
TOUCHPAD_BUTTON = 16

LS_LR_AXIS = 0
LS_UD_AXIS = 1
RS_LR_AXIS = 2
RS_UD_AXIS = 3
L2_AXIS = 4
R2_AXIS = 5

L1_PASSIVE_VAL = L2_PASSIVE_VAL = -1.0
